# Generated by Django 3.2.7 on 2021-09-11 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
                ('forum_name', models.CharField(max_length=100)),
                ('forum_description', models.TextField()),
                ('forum_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('forum_creator', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-forum_date_created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=50)),
                ('comment_content', models.TextField(max_length=500)),
                ('comment_date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('forum_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='forum.forum')),
            ],
            options={
                'ordering': ['-comment_date_posted'],
            },
        ),
    ]
